### ISSUE TITLE
Move Wiki as Polykey-Docs repository acting as a CMS for polykey.io/docs

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Docs#1]
The wiki will be scheduled to go into the polykey.io/docs instead due to https://github.com/github-community/community/discussions/4992. GH wikis are not SEO friendly.

However the wiki is still useful way of editing information compared to editing pages on our website. So a hybrid solution is to have the wiki available but then replicate/mirror the wiki to the website.

How to do this? Well the wiki information is public, and we can use BE server to mirror the information. Because search engines cannot see the wiki anyway, it's fine to have the duplicate information.

However `polykey.io` is hosted by webflow which has their own custom CMS. So how to connect to an external API (possibly serverless) backend to then load custom data. Most important it must do the rendering of HTML itself, and not just a mirror the HTML and present it via SSR, not fetched from JS.

It looks like on webflow, it supports https://university.webflow.com/lesson/href-prefix which allows part of an existing website hosted by your own webserver to reverse proxy a particular url directory to webflow.

However I'm looking to do the opposite, use webflow to reverse proxy a portion of the site to an alternative location. However they only allow this for enterprise: https://webflow.com/feature/reverse-proxy-service-for-enterprise

So it looks like it will be time to to front webflow with our own reverse proxy to serve.

There are 2 options here:

1. Use cloudflare - it is already fronting `polykey.io` and we can use it's page rules and maybe other features to be able to route a subdirectory to a different backend server.
2. Run our own system on AWS, and do the routing there, and upstream to webflow for the CMS and main site... etc. Hopefully the ALB is sufficient for this.

Finally the underlying backend could work as a serverless platfrom like cloudflare workers, and then it just has to fetch the wiki markdown and render the correct page.

This does limit the wiki's formatting to what the HTML is shown. See: https://stackoverflow.com/questions/38480701/can-a-github-wiki-embed-html and https://github.com/bryanbraun/github-wiki-html-test/wiki. Note that even if github wiki itself removes those tags, the code is still in the wiki git, and when we mirror we can render that with custom CSS as well if needed. We will need to incorporate this https://webmasters.stackexchange.com/a/76927

Seems like something to be automated with pulumi when we get to it.

### Tasks

- ~[ ] 1. Create server backend for fetching wiki source from https://github.com/MatrixAI/Polykey.wiki.git~ - unnecessary as we use SSG triggered from CI/CD
- [x] 2. Server backend should be runnable on a "serverless" worker like cloudflare workers
- ~[ ] 3. Server backend should be caching the git repository, and just fetching changes should be fast, this means filesystem state may need to be cached, either via mounted filesystem, ephemeral storage is fine~ - this is not necessary, as we change to using SSG triggered in the CI/CD
- [x] 4. Serve a simple home page from the wiki rendered markdown
- [x] 5. Try out Cloudflare's page rules in order to route to a server from `polykey.io/docs`
- ~[ ] 6. Need to integrate the theme appropriately, it's not possible to partially load data from a third party inside webflow template on the backend, only custom code on the frontend, so docs server will need to satisfy the same HTML header and footer of the main website~ - #6
- ~[ ] 7. Reuse the polykey.io theme, could be done through a git submodule pointing to website theme code~ - #6
- [x] 8. Integrate https://docusaurus.io/ as a SSG framework for rendering the wiki

**Comment by CMCDragonkai** [comment]
https://blog.cloudflare.com/subdomains-vs-subdirectories-improved-seo-part-2/ - here is an example using workers to do proxying.

Now one issue talked about there is important. If the asset paths like `/images` are coming out of the root domain, that would mean that the docs pages are loading images like `polykey.io/images/X`. But these images are actually in the CF pages domain, and not under the main `polykey.io`.

We would need the images to be instead loaded from `polykey.io/docs/images`. But we still want to preserve the paths on GitHub too...

**Comment by CMCDragonkai** [comment]
In working with cloudflare workers, pages has their own workers system integration. This is called cloudflare pages functions. https://developers.cloudflare.com/pages/platform/functions/

There are 2 ways of deploying these functions, using a `functions` directory under the `dist`, or using `_worker.js` which allows one to write a function for the entire pages domain.

However I discovered another bug https://github.com/cloudflare/wrangler2/issues/1570, it doesn't work unless I'm running the `wrangler pages publish ./` on the current directory.

This is still very much a beta product, so there's lots of little polishing issues here.

At any case this doesn't actually solve my problem. These worker functions still sit within the cloudflare pages system, and is not routable unlike workers as subpaths of existing domains.

So I'll need to instead deploy a proper worker, and not just cloudflare pages.

Perhaps... it's possible to use worker sites instead, it seems to work the same as a worker. Let's see what happens if I were to deploy a worker-site instead of a normal worker. A template is provided here: https://developers.cloudflare.com/workers/platform/sites/start-from-scratch

**Comment by CMCDragonkai** [comment]
Ok moving to cloudflares workers sites worked. This is basically the same as a normal cloudflare worker, but instead it has `[sites]` section in the `wrangler.toml` that specifies a `bucket = "./public"`. I've pointed the build to now `public` as it makes more sense as it is not a distribution.

It basically uploads every file in the public directory to the cloudflare KV system. Which is key-value database globally distributed like a cache. Every file has a unique file path, the entire file path is the key.

The KV is given a "namespace" and an environment variable binding:

![image](https://user-images.githubusercontent.com/640797/181505518-aebce128-1a39-432a-9a65-f208ba9d59b0.png)

![image](https://user-images.githubusercontent.com/640797/181505722-4b64ff24-2282-48ec-bcf4-15163d83796b.png)

As you can see the values of the KV is just the full content of the files verbatim. In a way it just looks like a S3 bucket, but it does have slightly different consistency behaviour compared to durable objects.

**Comment by CMCDragonkai** [comment]
It's actually really easy to migrate between workers sites and cloudflare pages, and cloudflare pages is really missing this critical feature. So instead of the `_worker.js` script, you can have a full JS-based worker application inside the `src`. This can contain typescript, webpack configuration... etc. It appears cloudflare takes the contents of `src` and also does build processing on it and supports external packages installed in the project repo.

Alot of the features and behaviour of wrangler is hard to find clear explanations of.

So now `polykey.io/docs` and `polykey.io/docs/*` both route to the worker code in `src/index.ts`. Now we just need to write the code `src/index.ts` to actually properly route to the static content. Probably by referencing `__STATIC_CONTENT`.

Note that there's no such thing as different environments for cloudflare workers. They are just deployed to separate cloudflare workers.

![image](https://user-images.githubusercontent.com/640797/181506595-7f6d05bb-2504-4f3e-8443-0a169f425efb.png)

This is unlike cloudflare pages which does support it.

Finally cloudflare worker sites is basically the same as cloudflare workers, it just does some extra automation regarding the KV upload of static assets.

Note that there is no authentication to any of these things, any auth has to be done inside the worker code. Otherwise, they have to be routed via a custom domain or a custom route that then can have cloudflare stick their firewall/access/zero trust system on top.

**Comment by CMCDragonkai** [comment]
Cloudflare pages does appear to be a more sophisticated product, with a lot of convenience features for any kind of site deployment (the integration of functions allows a fully dynamic PHP-CGI-esque kind of site).

![image](https://user-images.githubusercontent.com/640797/181507222-299681f5-61bf-474d-9984-ed267911a6d4.png)

I suspect that once the routing feature becomes available to cloudflare pages, it should be simple enough to transition back to pages, while for now we stick to using worker sites.

**Comment by CMCDragonkai** [comment]
Ok, after some wrangling, some further notes:

1. It seems `@cloudflare/kv-asset-handler` has problems with assets that have spaces in their names. That is requesting `Polykey Logo.png` is problematic but `divio_quadrant.png` is no problem. This may be due to HTML entities of `%20` not being processed properly.
2. URLs with `/images/X` is referenced from `polykey.io/images/X`, this is wrong, and needs to be fixed to point to `polykey.io/docs/images` that is offset from where the main URL is.
3. The offsetting seems to work automatically with docusaurus when it has its `baseUrl` set to `docs`. This causes all of its assets to be loaded as `polykey.io/docs/images`. However because docusaurus does not process `<a>` tags, these links are left as `/images` and not `/docs/images`.
4. When using `![]` it does in fact process it, but turns it into `/docs/assets/images` because it does some processing on the asset itself.
5. When docusaurus processes assets, it does add a sequence of characters to them. When cloudflare uploads, it also adds another sequence. The end result is a file looking like: `assets/images/divio_quadrant-8b21327c9a55ca08c6712f26bda2113c.28b2f60045.png`. The former is added by docusaurus, the latter by cloudflare.

Ok so basically it is correct to set the `baseUrl` to `/docs/`, this allows docusaurus to generate links relative to `/docs/`.

Additionally we need to also process the `<a>` tags, either by adding a base tag, or by using the remark plugin to process anchor tags as well without special require calls. If we use the require calls, it won't look nice in github.

**Comment by CMCDragonkai** [comment]
Relevant:

* https://github.com/facebook/docusaurus/pull/1831#issuecomment-1196972093
* https://github.com/facebook/docusaurus/discussions/6465#discussioncomment-2040501

I'm thinking... these are 2 solutions to the same problem. Either apply some base tag that affects how my a href links are loaded, or do some post-processing on src tags and more...

Alternatively we do definitely say `/docs/images`, but then provide symlinks in the `/docs` directory to `/images` in the repo. So canonical location is `/images` in the repo, but then we symlink `/static/images -> /images` AND `/docs/images -> images`. If this works, it's likely the easiest way that doesn't involve adding a custom tag or doing custom post-processing.

Furthermore need to try to use asset paths without any spaces in the names. Although this should likely be fixed upstream by cloudflare.

**Comment by CMCDragonkai** [comment]
Nope the `/docs/images` idea doesn't work for GitHub wiki. Symlinks don't render properly. That scraps that idea.

So that leaves either using a base url or post processing `img` tags and `anchor` tags appropriately...

**Comment by CMCDragonkai** [comment]
Note that cloudflare has some protections for the workers:

1. Firewall rules via the WAF
2. Rate limiting

The rate limiting is actually not worth it because it's more expensive than just executing the workers themselves. You may as well just pay the cost of worker execution as part of the bundled plan. It can be useful if you want to rate limit IPs specifically to allow fair usage across different client IPs.

This leaves the firewall, which you can set rules to block certain traffic. By default cloudflare does not have any kind of layer 7 protection. This has to be done manually via the WAF.

**Comment by CMCDragonkai** [comment]
Posted new bug: https://github.com/cloudflare/kv-asset-handler/issues/331.

**Comment by CMCDragonkai** [comment]
Ok what's left to do is:

1. Force processing of anchor links and img src tags so that `/images` works.
2. Fix the side bar so we can use a custom layout
3. Bring in the Polykey theme as a custom theme - this can be done later as separate issue

**Comment by CMCDragonkai** [comment]
So docusaurus uses 2 types of plugins in process markdown: remark and rehype. Remark works on the markdown AST, while rehype works on hypertext AST.

It seems pretty simple to create these plugins https://docusaurus.io/docs/markdown-features/plugins#creating-new-rehyperemark-plugins. So I'm still not entirely sure which one is the right one for finding the `<img src="" />` attribute so let's just do recon by fire (or a sanity check).

**Comment by CMCDragonkai** [comment]
The image links are all sorted now. 

I got 2 versions of the plugin:

```js
/**
 * Docusaurus does not process JSX `<img src ="...">` URLs
 * This plugin rewrites the URLs to be relative to `baseUrl`
 * Markdown links `[]()`, images `![](/image)` and anchor `<a href="...">`
 * are already automatically processed
 */
const remarkImageSrcWithBase = (options) => {
  return (ast) => {
    visit(ast, 'jsx', (node) => {
      const matches = node.value.match(/^(<img\s.*?src="\s*)\/(.*)$/);
      if (matches != null) {
        node.value = `${matches[1]}${baseUrl}${matches[2]}`;
      }
    });
  };
};

/**
 * Docusaurus does not process JSX `<img src ="...">` URLs
 * This plugin rewrites the src attribute to `src={require("...").default}`
 * Markdown links `[]()`, images `![](/image)` and anchor `<a href="...">`
 * are already automatically processed
 */
const remarkImageSrcWithRequire = (options) => {
  return (ast) => {
    visit(ast, 'jsx', (node) => {
      const matches = node.value.match(/^(<img\s.*?src=)"(\s*\/.*?)"(.*)$/);
      if (matches != null) {
        node.value = `${matches[1]}{require("${matches[2]}").default}${matches[3]}`;
      }
    });
  };
};
```

I think the second one is better as that always uses the `require()` as markdown images would normally do.

**Comment by CMCDragonkai** [comment]
Along the way, I also fixed the links to `/blog`... etc, which were previously suffixed to the `baseUrl` of `/docs/`. This is not well documented but:

```
            {
              label: 'Blog',
              href: '../blog',
              target: '_parent',
            },
```

Is needed, the using `href` and `../blog` ensures that we get `/blog` rendered without `/docs/blog`. Then the `target: '_parent'` is necessary to ensure that the link resolves using the browser and not the JS HTML router (as it is leaving the SPA app).

**Comment by CMCDragonkai** [comment]
But on the topic of SPA. I've discovered a new bug. If you go to `http --verbose HEAD https://polykey.io/docs/ACL` you get a 404.

However the JS takes over and then routes properly to `docs/ACL`. Which is why in the browser you still see the ACL page afterwards. However HTTP-wise, it's a 404.

I think the cloudflare worker is finding that it doesn't find `ACL`. However `http --verbose HEAD https://polykey.io/docs/ACL.html` does work.

This means I need to make the KV handler route as if it's an SPA. It needs to understand that `/docs/ACL` is the same as `/docs/ACL.html`.

**Comment by CMCDragonkai** [comment]
Ok so we don't want to use SPA routing, since we do want it to show the right file on the first load for SEO purposes.

In this case, we need to ensure that either `trailingSlashes: true` or `undefined`. If it is `true` it seems to create another problem. This causes relative links to be relative to the last trailing slash. Which seems incorrect.

So `trailingSlash: undefined` is the only solution. This is what generates directories.

In cloudflare the KV asset loader will resolve things that look like directories to `dir/index.html`, which is what we will need.

However if `/dir/` link is fetched, this will still be acceptable. We may want to provide a redirect to rewrite `/dir/` to `/dir`. This has to be a `308` redirect. Otherwise relative links will end up not working.

**Comment by CMCDragonkai** [comment]
Ok so the full solution was even more complicated. You need this too https://docusaurus.io/docs/markdown-features/links.

Basically this means we must use `[Blah](./Blah.md)` links, rather than just `[](Blah)`.

They are considered file links. And file links get "processed" by docusaurus. This removes the `.md`.

On Github these links work, while `Blah` does not. This is because I transitioned from the wiki where those links did work, but these links do not.

So now with `trailingSlashes: undefined` and file links, then everything works. Even `[](Home)` properly gets processed into just `/docs/` instead of `/docs/Home`. But there is a redirect from `/docs/Home` to `/docs`.

**Comment by CMCDragonkai** [comment]
Ok this is all done. Cool so we have an SPA that is SEO-capable (that is pretty much hydrated statically), but with SPA routing in JS. Future custom functionality can be extended with teh workers.

Lastly:

1. Fix the side bar so we can use a custom layout
2. Bring in the Polykey theme as a custom theme - this can be done later as separate issue

Will be done in a new issue.

I'll setup the `docs` link in `polykey.io` to point to the new docs polykey.io/docs.

**Comment by CMCDragonkai** [comment]
Webflow now feels slow compared to the docs because the docs is a SPA. I've a plan to switch over the blog to docusaurus too if we make use of it more... Then webflow becomes purely a page designer for the front page.

**Comment by CMCDragonkai** [comment]
Should write a blog post about this.

**Comment by CMCDragonkai** [comment]
It's actually not necessary to do this. https://github.com/MatrixAI/Polykey-Docs/issues/1#issuecomment-1200173866

You can use `..` or `.` to refer to directories and this is understood. I'm now using `README.md` as the "index" page for a given category.
