### ISSUE TITLE
Setup CI to match the feature/staging/master procedure in polykey.com

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Docs#36]
This way `dev.polykey.com`, `feature.dev.polykey.com`, `staging.polykey.com`, and `polykey.com` will all have their version of the docs, depending on what the status of the docs is.

### Tasks

- [x] 1. Setup feature, staging, master branches.
- [x] 2. Configure this repo to default to `staging` as well as github's repo
- [x] 3. Configure the `wrangler.toml` with a `scripts/deploy.js` similar to `polykey.com`, but remember it's necessary to use routing rather than `custom_domain`.

**Comment by CMCDragonkai** [comment]
Ok so in #49, I was able to replace this all across `master` and `staging`. However there's a problem with the deploy script.

Feature branches are expected to deploy to things like `feature-x.dev.polykey.com/docs/`.

However if I setup a route like that, that doesn't actually guarantee that `polykey.com` has that same feature branch.

Only the polykey.com workers can deploy a custom domain. We want the docs worker to always just use routing. So this is unlikely to work.

If we could instead setup a custom domain for just the docs - that would only work for the feature branches here. And in fact there could still be a conflict with `feature-x.polykey.com` worker - if one were to create 2 branches, one on polykey.com, one here, and use the branch name.

It's really weird, cause basically the docs worker cannot deploy their own custom domain for fear of conflict with polykey.com, but it's also unlikely that the feature branch with the same name would exist in `polykey.com`.

So I guess the deploy script could try to deploy a custom domain... under `feature-x.polykey.com` too, but then it would be quite confusing.

**Comment by CMCDragonkai** [comment]
This is done with 68e56f7e58ce94911dc998500cd6c1eeecbc5a50 and bfc678c28d93c3c5e52facbc6b3ee40ea943bc5f.

So for now feature branch deployments may not quite work unless there is also a custom domain setup by polykey.com.

In short one has to have the same feature branch name between polykey.com and polykey-docs.

So that means feature branch deployments are probably not really suitable. @CryptoTotalWar this means you would need to instead just push to staging to see how it goes for now. Later in the future, I can delegate you the auth details for you to push to `dev.polykey.com/docs` so maybe that will be easier.

**Comment by CMCDragonkai** [comment]
These 2 PRs due to the lfs fix on the files have to be recreated - by checking out from the `staging` branch now.

* https://github.com/MatrixAI/Polykey-Docs/pull/42
* https://github.com/MatrixAI/Polykey-Docs/pull/33

@CryptoTotalWar please be aware of this, and create them asap.

**Comment by CMCDragonkai** [comment]
Disabling force pushes now.

**Comment by CMCDragonkai** [comment]
This is done.

**Comment by CMCDragonkai** [comment]
As a side-effect of doing this, the 404 problem got solved too. The basic rule is that this must always be the case for CF worker deployments:

```
  // This ensures that `/x.md` is generated as `/x/index.html` and not `/x.html`.
  // Which is the expected directory layout for most web servers.
  trailingSlash: undefined,
```

**Comment by CMCDragonkai** [comment]
This was done in bfc678c28d93c3c5e52facbc6b3ee40ea943bc5f
