### ISSUE TITLE
Write Wiki Page for Decentralized Trust Network

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Docs#5]
### Specification
Our polykey-design repo has lots of information on how DIs and Gestalts and Social Discovery works.

* https://gitlab.com/MatrixAI/Engineering/Polykey/polykey-design/-/issues/31 - Digital Identities - KN Identity and DI Augmentation
* https://gitlab.com/MatrixAI/Engineering/Polykey/polykey-design/-/issues/33 - Gestalt Trust
* https://gitlab.com/MatrixAI/Engineering/Polykey/polykey-design/-/issues/27 - Social Discovery

All of this information should be synthesized into the Polykey wiki, the js-polykey wiki should be focused on the CLI-side of the situation.
### Additional context
The wiki page can be found here: https://github.com/MatrixAI/Polykey/wiki/Decentralized-Trust-Network
### Tasks
- [x] Compile linked issues into notes
- [x] Compile notes into skeleton
- [x] Write draft version of article (deadline Friday July 9th)
- [ ] Final check over/final version

**Comment by CMCDragonkai** [comment]
Closing this as this is mostly done it will require reviewing the content later.
