### ISSUE TITLE
Polykey-Docs CLI Tutorial: Feature-Launch-Revamp-Fix

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#52]
### Tasks

- [x] 0. Manually add changes from the feature-launch-revamp branch (https://github.com/MatrixAI/Polykey-Docs/pull/33)
- [ ] 1. Add a getting started section under https://polykey.com/docs/tutorials/polykey-cli/

**Comment by CryptoTotalWar** [comment]
So this branch will be mostly repurposed for adding the feature-launch-revamp additions into the new feature-getting-started branch. 

I already identified an approach and identified the difference in "A", "M" and "D" files. 

Will primarily focus on the "A" documentation-related files from the old branch that will need to be cherry picked (or manually added) into the new branch. 

To do this, I will clone the repo for the feature-launch-revamp branch. 

This way i can have 2 instances of VS side-by-side. One with the new branch and one with the old. This way i can also locally deploy both at the same time in order to view the additional files in the old branch and identify if they should in fact be cerry picked into the new branch. 

I marked this assignment on the standup items as an L. 

My ETA for this procedure to be completed it by tomorrow morning Sydney time.

**Comment by CryptoTotalWar** [comment]
Based on the `git diff --stat` output, you can observe the following changes between the `feature-launch-revamp` and `feature-getting-started` branches:

### Summary of Changes

1. **Files Added/Modified:**
   - `.eslintrc`
   - `docs/development-guide/development-environment.md`
   - `docs/reference/polykey-cli/commands/polykey agent.md`
   - `docs/reference/polykey-cli/commands/polykey bootstrap.md`
   - `docs/reference/polykey-cli/commands/polykey identities.md`
   - `docs/reference/polykey-cli/commands/polykey keys.md`
   - `docs/reference/polykey-cli/commands/polykey nodes.md`
   - `docs/reference/polykey-cli/commands/polykey notifications.md`
   - `docs/reference/polykey-cli/commands/polykey secrets.md`
   - `docs/reference/polykey-cli/commands/polykey vaults.md`
   - `docs/reference/polykey-core/gestalts.md`
   - `docs/reference/polykey-core/identities.md`
   - `docs/reference/polykey-core/network.md`
   - `docs/reference/polykey-core/nodes.md`
   - `docs/reference/polykey-core/sessions.md`
   - `docusaurus.config.ts`
   - `files/CARL.puml`
   - `files/Other Solutions.md`
   - `files/polykey-vision.excalidraw`
   - `files/session-interception.puml`
   - `files/session-management.puml`
   - `images/network-1.png`
   - `images/network-2.png`
   - `images/quic-1.png`
   - `images/quic-2.png`
   - `images/quic-3.png`
   - `images/quic-4.png`
   - `images/rpc-1.png`
   - `images/rpc-2.png`
   - `package-lock.json`
   - `package.json`
   - `shell.nix`
   - `sidebars.ts`
   - `tsconfig.json`
   - `worker.ts`
   - `wrangler.toml`

2. **Files Removed:**
   - `design/LICENSE`
   - `design/Polykey Architecture.excalidraw`
   - `design/Polykey Journey to Launch.excalidraw`
   - `design/Polykey Testnet_Mainnet Dashboard Architecture.excalidraw`
   - `design/Polykey's Comparisons.excalidraw`
   - `design/Polykey's Decentralised Trust Infrastructure.excalidraw`
   - `design/Polykey's Introduction to the Delegation of Authority.excalidraw`
   - `design/Polykey's Zero Trust Workflows.excalidraw`
   - `design/TLS Situation in Polykey.excalidraw`
   - `docs/LICENSE`
   - `docs/development-guide/docker.md`
   - `docs/reference/polykey-cli/commands/agent.md`
   - `docs/reference/polykey-cli/commands/bootstrap.md`
   - `docs/reference/polykey-cli/commands/identities.md`
   - `docs/reference/polykey-cli/commands/keys.md`
   - `docs/reference/polykey-cli/commands/nodes.md`
   - `docs/reference/polykey-cli/commands/notifications.md`
   - `docs/reference/polykey-cli/commands/secrets.md`
   - `docs/reference/polykey-cli/commands/vaults.md`
   - `files/LICENSE`
   - `files/README.md`
   - `images/LICENSE`
   - `images/README.md`
   - `scripts/deploy.js`
   - `server/worker.ts`

### Understanding the Changes

- **Additions (+9920 lines):** These are the new lines or new content added in the `feature-launch-revamp` branch compared to the `feature-getting-started` branch.
- **Deletions (-104475 lines):** These are the lines removed or content deleted from the `feature-launch-revamp` branch compared to the `feature-getting-started` branch.

**Comment by CryptoTotalWar** [comment]
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ bootstrap.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ identities.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ keys.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ nodes.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ notifications.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ secrets.md
- [ ] feature-launch-revamp:docs/reference/polykey-cli/commands/polykey\ vaults.md
- [ ] feature-launch-revamp:files/Polykey\ Elliptic\ Curve\ Hybrid\ Integrated\ Encryption\ Scheme.excalidraw
- [ ] feature-launch-revamp:images/network-1.png
- [ ] feature-launch-revamp:images/network-2.png
- [ ] feature-launch-revamp:images/quic-1.png
- [ ] feature-launch-revamp:images/quic-2.png
- [ ] feature-launch-revamp:images/quic-3.png
- [ ] feature-launch-revamp:images/quic-4.png
- [ ] feature-launch-revamp:images/rpc-1.png
- [ ] feature-launch-revamp:images/rpc-2.png
- [ ] feature-launch-revamp:worker.ts

**Comment by CMCDragonkai** [comment]
Excalidraw files should be loaded into excalidraw, then you need to extract out subsections as SVGs, and put them as files, and represent them as nicely readable docs. 

See how I did this here https://github.com/MatrixAI/Orchestrator/issues/5 - I did it as part of an issue spec, you should do this as part of docs creation.

**Comment by CMCDragonkai** [comment]
I was doing some coding work as well, but you can ignore anything that was not `/docs` related from the old PR.

But you should also be tackling the getting started specifically together with any changes you need to synthesise.

**Comment by CryptoTotalWar** [comment]
> I was doing some coding work as well, but you can ignore anything that was not `/docs` related from the old PR.
> 
> But you should also be tackling the getting started specifically together with any changes you need to synthesise.

I think i'm done auditing the docs. 

There were some files and images that i transferred over as well. 

I am going to reframe from removing any files from the files removed section unless you think its necessary as well. 

The last thing i need to do is verify that the sidebars.ts is configured correctly and then do checks for the buld to mark the PR ready for review. 

After you review the additions, I can start incorporating the getting started Epic work.

**Comment by CryptoTotalWar** [comment]
Some of the modifications made under 

`docs/reference/polykey-core/` 

are somewhat questionable and should be reviewed in the PR

@CMCDragonkai 

I fixed deployment errors. Running the sanity checks now to make PR Ready for review. ETA 10 minutes.

**Comment by CMCDragonkai** [comment]
Reference docs then to be out of date quickly because they really should be autogenerated from the code. We actually do autogenerate via `npm run docs` in the respective repos, but we have not actually taken them out of the repos yet… - I imagine we might just link to the relevant libraries for any "reference docs" on their github page deployments.

**Comment by CMCDragonkai** [comment]
So is this the "first task" under https://github.com/MatrixAI/Polykey-Docs/issues/9?
