### ISSUE TITLE
PK-Docs (reference/poykey-cli) Create directory for primary commands to have sub-command mappings 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#63]
### Tasks

- [ ] 1. Adjust primary commands to have a folder with a README.md and multiple other markdown files under the folder that have the docs for sub-commands 
- [ ] 2. Adjust sidebars.ts 
- [ ] 3. review

**Comment by CMCDragonkai** [comment]
It's just a matter of using `index.md` for the main command like `agent/index.md` then sub commands `agent/start.md` and `agent/stop.md`.

**Comment by CMCDragonkai** [comment]
Unless there's a PR here, this is in todo, not in-progress.

**Comment by CryptoTotalWar** [comment]
> It's just a matter of using `index.md` for the main command like `agent/index.md` then sub commands `agent/start.md` and `agent/stop.md`.

Based on the feedback here: 

- The intention with this ticket is to flesh out reference category documentation for the Polykey-CLI commands. 

[x] Create a Polykey-CLI category container under the Reference Section. This already exists. https://polykey.com/docs/reference/polykey-cli/

The README for the Polykey-CLI only contains 1 card because theres 3 levels in this tree. 

**Polykey-CLI** - Reference section Category Container 
- [**Commands**](https://polykey.com/docs/reference/polykey-cli/commands/) - This serves as a high-level overview "city map" of all the primary & sub-primary commands in Polykey-CLI. 

- [ ] The README for the Commands page seems to be sufficient at the moment so revamping it isn't fully necessary but the index pages for each individual primary command is lacking!!! In the future, i'd like for the overview page of Polykey-CLI commands to serve more as a high-level overview where the individual index pages for each primary command breaks down into depth and detail. 

- [ ] Need to spec out the requirements for the PR in which we will largely need to focus on providing detailed handwritten reference information for the polykey primary commands. 

Each sub-command can have its own index page for breaking down further detail. I would like the card lists to be at the top of each primary command index page for easier navigation. 

This ticket is perfect timing for cycle 10 because there's prior PK-CLI documentation in the tutorials section that needs to be migrated here. I can use this ticket for tracking the initial migration, page structure-set-up requirements, and proliferation of additional requirements. 

1. first step is setting up the page strucute. ~ S
2. next is configuring the sidebars.ts ~ XS  
3. migrating existing info from getting started to the relevant pages ~ M 
4. fleshing out the rest of the info ~ L
