### ISSUE TITLE
PK-Docs: Onboarding Sujay as a dev rel contributor for PK Docs 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#74]
### Tasks

Two hour meeting slot on Tuesday with Sujay. 

- [x] 1. Meeting on Tuesday with @sujaycarkey to clone & set-up the repo
- [x] 2. Explain some of the standards and workflow's in OS Polykey  with issue tickets, git, etc. 
- [x] 3. Review the Divio System 
- [ ] 4. Discuss feedback/revamp of the PK-CLI Tutorials 
- [ ] 5. Review Hadera documentation 
- [ ] 6. Scope demo for Hadera dotenv

**Comment by CryptoTotalWar** [comment]
@sujaycarkey you said you had some notes and feedback on the PK-CLI tutorials. 

I also took some notes on the PK-CLI tutorials... we need to find time to share notes. 

Essentially, I believe a lot of the current tutorial doc is better suited for re-purposing into the reference guides!
