### ISSUE TITLE
PK-Docs Installation Instructions for Windows 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#77]
### Tasks

- [ ] 1. Try downloading PK for Windows 
- [ ] 2. The process should be somewhat similar to the installation instructions for Linux and Mac
- [ ] 3. Get it to work and document the process in a structure similar to how its written for Mac OS download instructions. 

Notes/Tips:

- when you create a PR, make sure you pull the latest from staging and create a PR that started with the name <feature-x-y-z> 
  - In other words, the feature branch you create must start with the word "feature" followed by a "-" 
- once you make an initial commit to your new feature branch, you can push it remotely. 
- Then on GH you will see the option to create a PR for this new branch. 
- The PR template that you will fill out, will be for making the PR from the feature -> staging 
- In the PR template, where it says, this PR solves issue # x, you put that it solves this issue 

- Keep pushing your changes to the PR from your feature branch and when its ready to review, ping me.

**Comment by CryptoTotalWar** [comment]
@sujaycarkey I am moving this ticket to backlog. Let me know when you plan on actioning this ticket.
