### ISSUE TITLE
Fix Sidebar

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Docs#8]
The side bar on the original wiki is currently just a page `docs/_Sidebar.md`.

We want to re-use this structure in the docs page, and have it represented properly.

The side bar should also be able to hide half-baked pages. We may need a way to label pages that are half-baked and shouldn't be shown.

### Tasks

- [x] 1. Extract information out of `_Sidebar.md`
- [x] 2. Place it into `sidebars.js`
- [x] 3. Update the `polykey.io/docs`

**Comment by CMCDragonkai** [comment]
If a particular doc id doesn't appear in the side bar, the sidebar does not get listed for that page. See: https://github.com/facebook/docusaurus/issues/3562#issuecomment-1305121918

This is explained here: https://docusaurus.io/docs/sidebar/multiple-sidebars

**Comment by CMCDragonkai** [comment]
To fix this, the Home.md has an additional front matter:

```
displayed_sidebar: docs
```

And now the sidebar displays even if I don't put the `Home` into the sidebar, since the `Home` is likely to be in the navigation anyway.

**Comment by CMCDragonkai** [comment]
The reference section has a lot of articles that isn't well sorted out at this point in time.

Furthermore all the articles are flat, with no subdirectories. This does require every documentation article to have a unique name. The reference sidebar in particular may require the ability to re-use certain names.

I'll check if this is possible.

**Comment by CMCDragonkai** [comment]
Yes it is possible.

We can do something like this:

```
├── reference
│   └── keys
│       └── cryptography.md
```

And then the URL is then `polykey.io/docs/reference/keys/cryptography`.

But by using `# Cryptography` at the top, it sets both the "title" and the initial heading.

We can customise this in a number of ways.

By setting the front matter `title: Cryptography` this affects both the web title and the initial heading.

But `# Cryptography` is good enough and it is actually markdown, plus it looks good on the github rendering too compared to using the front matter.

So now the URLs can all be made lowercase and the file names can be lower case too. And we can structure our documentation according to the routing structure.

**Comment by CMCDragonkai** [comment]
The reference category loosely follows the domain directories we have in `Polykey`. However they don't actually need to strictly follow it, because the reference documentation again is still a "user's documentation" and not developer documentation.

However some users cross over into developers, and that's why the reference documentation is useful.

I think the reference should cover "high level domains", and maybe some useful lower level domains, but it shouldn't go into the detail of actual code itself. Instead it should cover them as components and understand what their responsibility is, what kind of schema it is dealing with, and what kind of state it is dealing with...

Actual code depends on function signatures which is likely to change quite often so it's not worth documenting. And we have auto generated docs for that.

**Comment by CMCDragonkai** [comment]
This is done with #9b8dc1f83036083aa13ecbfb0000980c98c54376.

**Comment by CMCDragonkai** [comment]
![image](https://user-images.githubusercontent.com/640797/200481334-dd57c537-2ac5-4896-b1cc-6cbfe9523e4c.png)
