### ISSUE TITLE
Revamp Documentation for Updated Unix Commands in Polykey CLI

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#95]
### Description

This ticket is dedicated to updating the Polykey documentation to incorporate the newly integrated Unix-style commands within the pk secrets subsystem. The goal is to ensure that all instructional materials are up-to-date, reflecting the new command functionalities to enhance clarity and usability for end users.

### Tasks and Notes

- **Determine Release Strategy**: 
  - [ ] Decide if the CLI updates will be released all at once or in phases.
  - [ ] Plan to start detailing and implementing documentation updates 2 weeks prior to the first release.

- ** Implementation Task Tracking:**: 
  - [ ] Create and maintain a checklist for updating various sections of the documentation to align with the CLI changes.
 
- [ ] **Set Up Test Environment** (Optional):  Establish a test environment that mirrors the new CLI version to allow for hands-on interaction and verification of documentation accuracy.

### Placeholder for Detailed Documentation Updates

**Overview of Documentation Areas Needing Updates**:

- [ ] Docs Home Page 

- [ ] Getting Started Sections 

- [ ] Reference Sections 

- [ ] How-To-Guides 

- Blog Posts 

  - [ ] X

  - [ ] Y

**Comment by aryanjassal** [comment]
What do we do with this issue? It looks underspecced and abandoned.

**Comment by tegefaulkes** [comment]
Not sure. It still needs to be done to reflect the new unix style commands. But I'm unsure what the priority is for the documentation now.

The spec here will need to be rewritten and the issue added to the unix style commands project.

**Comment by aryanjassal** [comment]
> The spec here will need to be rewritten and the issue added to the unix style commands project.

This issue is already a part of the unix style commands project. That's how I discovered the existence of this issue in the first place.

This issue probably isn't high up in the priorities, so the documentation update will probably come near the end of the project.

**Comment by aryanjassal** [comment]
Should I just write up a quick paragraph or two of documentation whenever I add a new command? I tried to get my friend to use polykey, but he was struggling a bit because the documentation was out of date and I was the only one he could ask for documentation.

I might not be able to write up the final documentation, but at least the documentation would be usable for an end-user to try out the product.

**Comment by tegefaulkes** [comment]
Yeah, it would be great if you could write some updates.

**Comment by aryanjassal** [comment]
[https://github.com/MatrixAI/Polykey-Docs/pull/112](https://github.com/MatrixAI/Polykey-Docs/pull/112)

**Comment by aryanjassal** [comment]
Providing an example of using Polykey in a workflow would be pretty beneficial. We can probably make a separate page for "Using Polykey in your project", which could guide users through a setup similar to what we have with `secrets env` in nix shells. Later, when we have figured out how to handle this inside the CI, we can add a page for CI too.
